### ISSUE TITLE
Failure notification is sent before "started" one when task fails early

### ISSUE THREAD

**Issue by rshk** [getsentry/freight#37] opened 2015-08-12 09:43 UTC
Not a huge issue, but it might get confusing:

![2015-08-12_103828](https://cloud.githubusercontent.com/assets/434561/9220991/9412f65c-40de-11e5-871c-571bd89396ae.png)

I guess it's caused by https://github.com/getsentry/freight/blob/master/freight/notifiers/utils.py#L55-L62 (why not something like: `add to queue anyways -> if event == FINISHED then send all from queue`, btw?)

**Comment by dcramer** [comment] 2015-08-12 17:18
Dupe of #33 

We could do the queue thing, but I'd prefer if we just have a way to revoke the pending notification (theres other situations we sort of need to as well, where the queue takes a minute and then it ends up sending all of them)

**Closed by dcramer** 2015-08-12 17:18 UTC
